# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5), dtype=int)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
a=np.arange(10).reshape(2,5)
b=np.ones((2,5), dtype=int)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
d=np.array([[0, 1, 2, 3, 4], 
            [5, 6, 7, 8, 9]])
d.reshape(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
f=np.array([[[ 0,  1,  2,  3,  4],
             [ 5,  6,  7,  8,  9],
             [10, 11, 12, 13, 14]]])#its a (1,3,5) array
f.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [9]:
g=np.arange(15)
g.reshape (5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
h=np.random.randint(10, 30, size=25, dtype=int).reshape(5,5)
np.square(h)

## Question:8

### Create 5x6 an array and find the mean?

In [10]:
j=np.random.randint(10, 60, size=30, dtype=int).reshape(5,6)
np.mean(j)

31.6

## Question:9

### Find the standard deviation of the previous array in Q8?

In [11]:
k=np.std(j)
k

16.051168181786643

## Question:10

### Find the median of the previous array in Q8?

In [12]:
np.median(j)

27.0

## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
np.transpose(j)

array([[19, 53, 11, 31, 51],
       [52, 15, 19, 34, 50],
       [52, 22, 57, 18, 23],
       [23, 47, 57, 46, 11],
       [33, 20, 12, 42, 21],
       [10, 15, 41, 15, 48]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [14]:
m=np.random.randint(10, 60, size=16, dtype=int).reshape(4,4)
np.trace(m)

122

## Question:13

### Find the determinant of the previous array in Q12?

In [15]:
np.linalg.det(m)

-513587.99999999965

## Question:14

### Find the 5th and 95th percentile of an array?

In [17]:
p=np.random.randint(0, 100, size=50, dtype=int)
p5=np.percentile(p, 5)
p95=np.percentile(p, 95)
print("5th is",p5, "and 95th is", p95)

5th is 5.3500000000000005 and 95th is 88.0


## Question:15

### How to find if a given array has any null values?

In [18]:
ddd=np.array([9, 4, 1, 3, 4, 6, 6, 5, 9, 3, 0, 5, 0, 2, 5, 4])
np.where(ddd==0)

(array([10, 12], dtype=int64),)