# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [13]:
y=np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
x=np.arange(10,50,3)
x

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

4. Find the shape of previous array in question 3

In [7]:
x.shape

(10,)

5. Print the type of the previous array in question 3

In [10]:
x.dtype

dtype('float64')

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khurram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Khurram/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khurram/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

7. Print the dimension of the array in question 3


In [12]:
x.shape

(10,)

8. Create a boolean array with all the True values

In [14]:
z=y==0
z

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [19]:
twod=np.arange(8).reshape(4,2)
twod

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

10. Create a three dimensional array



In [20]:
threed=np.arange(8).reshape(2,2,2)
threed

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [24]:
rx=np.arange(8)
np.flip(rx)

array([7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [26]:
nv=np.zeros(10)
nv[4]=1
nv

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [31]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr=arr.astype('float64')
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [34]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
marr12=arr1*arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [35]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3=np.where(arr1>arr2, arr1, arr2)
arr3

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [36]:
arr4=np.arange(10)
arr5=arr4[arr4%2>0]
arr5

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [37]:
arr5=np.where(arr4%2>0,-1,arr4)
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [43]:
arr = np.arange(10)
np.put(arr, [5,6,7,8], [12])

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [44]:
x1=np.ones((5,5))
x1[1:-1,1:-1]=0
x1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [47]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [53]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0:-1,0:3]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [57]:
x2d=np.arange(10).reshape(2,5)
x1d=x2d[0,0:]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [60]:
y2d=np.arange(10).reshape(5,2)
y2d[1,1]

3

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [72]:
y2d=np.arange(9).reshape(3,3)
y2d[0:2,2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [77]:
randx=np.random.randn(10,10)
randx.min()
randx.max()

3.104006703588301

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([3,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 3, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [104]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [110]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[[np.where(names!='Will')],0:]

array([[[[ 0.47100597, -1.17104998, -0.74792625, -0.3155405 ],
         [-0.2571559 , -0.49185268,  0.01042992,  0.67649965],
         [ 0.89099165,  0.7855209 ,  0.47907897, -0.69002884],
         [-0.13570108, -0.14992071,  0.13183522,  1.83462523],
         [-0.86845341,  1.25140877,  0.53577683,  0.18204571]]]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [114]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data1=np.where(names!='Will')
data2=np.where(names!='Joe')
data[[np.intersect1d(data1, data2)],0:]

array([[[ 1.82955953,  0.35823874, -0.88337225,  0.63913529],
        [ 0.82255154, -1.26637926, -0.36172522,  1.65979743]]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [116]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [124]:
arr3d=np.random.uniform(1.0,16.0, size=(2,2,4))
print(arr3d)
#np.swapaxes(arr3d,2,2)

[[[ 4.00382358 13.8852988   8.62305453 13.52811495]
  [ 4.67827371 10.59017469 10.02225837  5.67272029]]

 [[11.36776421 13.46105761  6.58537015  4.35550231]
  [12.75231281  8.26495377  3.77188995  4.88796888]]]


33. Swap axes of the array you created in Question 32

In [125]:
np.swapaxes(arr3d,2,1)

array([[[ 4.00382358,  4.67827371],
        [13.8852988 , 10.59017469],
        [ 8.62305453, 10.02225837],
        [13.52811495,  5.67272029]],

       [[11.36776421, 12.75231281],
        [13.46105761,  8.26495377],
        [ 6.58537015,  3.77188995],
        [ 4.35550231,  4.88796888]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [145]:
sq=np.sqrt(np.random.uniform(0.1,0.5, size=10))
np.where(sq<0.5,0,sq)

array([0.        , 0.        , 0.        , 0.59762378, 0.57516552,
       0.        , 0.67790438, 0.60034363, 0.58393232, 0.52389218])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [153]:
a=np.random.randint(1,12, size=12)
b=np.random.randint(1,12, size=12)
np.maximum(a,b)

array([ 5, 10, 11,  3,  3, 10, 11, 11, 10, 10,  7,  3])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [159]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [198]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,4,8,9])
np.setdiff1d(a, b)

array([1, 2, 3])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [180]:
s = np.array([[34,43,73],
              [82,22,12],
              [53,94,66]])

t= np.array([[10,10,10]])
s[0:3,1]=t
s

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [168]:
x = np.array([[1., 2., 3.], 
              [4., 5., 6.]]) 
y = np.array([[6., 23.], 
              [-1, 7], 
              [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [167]:
matrix1=np.random.randint(1,50, size=(4,5))
print(matrix1)
np.cumsum(matrix1)

[[ 8 42  5  6 44]
 [ 6  8  3 18  8]
 [49  1 45 46 26]
 [ 2 13 43  3 13]]


array([  8,  50,  55,  61, 105, 111, 119, 122, 140, 148, 197, 198, 243,
       289, 315, 317, 330, 373, 376, 389], dtype=int32)